{{- if .Values.registry.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "github-actions-runner.registry.fullname" . }}
  labels:
    {{- include "github-actions-runner.labels" . | nindent 4 }}
  {{- with .Values.registry.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
