{{- if and .Values.registry.enabled .Values.registry.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "github-actions-runner.fullname" . }}-registry
  labels:
    {{- include "github-actions-runner.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  {{- with .Values.registry.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.registry.ingress.className }}
  {{- if .Values.registry.ingress.tls }}
  tls:
    {{- range .Values.registry.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.registry.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "github-actions-runner.fullname" $ }}-registry
                port:
                  number: 443
    {{- end }}
{{- end }}
