{{- if .Values.registry.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "github-actions-runner.fullname" . }}-registry-cleaner
  labels:
    {{- include "github-actions-runner.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry-cleaner
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600 # 1h
      activeDeadlineSeconds: 600 # 10m
      backoffLimit: 0
      template:
        metadata:
          name: {{ include "github-actions-runner.fullname" . }}-registry-cleaner
          labels:
            {{- include "github-actions-runner.labels" . | nindent 12 }}
            app.kubernetes.io/component: registry-cleaner
        spec:
          restartPolicy: Never
          enableServiceLinks: false
          automountServiceAccountToken: false
          securityContext:
            runAsNonRoot: true
            fsGroup: 65534
            fsGroupChangePolicy: "OnRootMismatch"
          containers:
            - name: {{ include "github-actions-runner.fullname" . }}-registry-cleaner
              securityContext:
                allowPrivilegeEscalation: false
                seccompProfile:
                  type: RuntimeDefault
                capabilities:
                  drop: ["ALL"]
                runAsUser: 65534
                runAsGroup: 65534
              image: "{{ .Values.registry.cleaner.image.repository }}:{{ .Values.registry.cleaner.image.tag }}"
              imagePullPolicy: {{ .Values.registry.cleaner.image.pullPolicy }}
              {{- with .Values.registry.cleaner.args }}
              args:
                {{- tpl (toYaml .) $ | nindent 16 }}
              {{- end }}
          {{- with .Values.registry.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.registry.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.registry.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
