apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluentd.fullname" . }}
  labels:
    {{- include "fluentd.labels" . | nindent 4 }}
data:
  fluent.conf: |-
    <label @FLUENT_LOG>
      <match fluent.*>
        @type null
      </match>
    </label>

    <source>
      @type http
      port 9880
      bind 0.0.0.0
    </source>

{{- range $key, $value := .Values.configMaps }}
    @include {{ $key }}
{{- end }}
{{- if .Values.metrics.enabled }}
    @include metrics.conf
{{- end }}

  # custom configs
{{- range $key, $value := .Values.configMaps }}
  {{ $key }}: |-
    {{ $value | nindent 4 }}
{{- end }}
{{- if .Values.metrics.enabled }}
  metrics.conf: |
    <source>
      @type prometheus
      port 24231
    </source>

    <source>
      @type prometheus_monitor
    </source>

    <source>
      @type prometheus_output_monitor
    </source>
{{- end }}
