apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keydb.fullname" . }}
  labels:
    {{- include "keydb.labels" . | nindent 4 }}
type: Opaque
data:
  common.conf: {{ include "keydb.commonConfig" . | b64enc }}
  {{- if .Values.backup.enabled }}
  walg.yaml: {{ include "keydb.walgYaml" . | b64enc }}
  {{- end }}
