apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongosync.fullname" . }}
  labels:
    {{- include "mongosync.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mongosync.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: sync
  template:
    metadata:
      annotations:
        checksum/config: {{ toJson .Values.config | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mongosync.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: sync
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mongosync.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      hostAliases:
        {{- toYaml .Values.hostAliases | nindent 8 }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --config=/etc/mongosync/mongosync.conf
            - --port={{ .Values.service.port }}
            {{- range $value := .Values.args }}
            - {{ $value | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /api/v1/progress
          #     port: http
          #     scheme: HTTP
          #   initialDelaySeconds: 10
          #   timeoutSeconds: 3
          #   failureThreshold: 30
          #   periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/mongosync
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: {{ include "mongosync.fullname" . }}
            defaultMode: 288
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
