{{- if false }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mongosync.fullname" . }}
  labels:
    {{- include "mongosync.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": {{ default "-15" .weight | quote }}
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: {{ default 600 .ttlSecondsAfterFinished }}
  activeDeadlineSeconds: {{ default 120 .activeDeadlineSeconds }}
  backoffLimit: {{ default 0 .backoffLimit }}
  completions: {{ default 1 .completions }}
  parallelism: {{ default 1 .parallelism }}
  template:
    metadata:
      labels:
        {{- include "mongosync.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: start
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      serviceAccountName: {{ include "mongosync.serviceAccountName" $ }}
      activeDeadlineSeconds: {{ default 600 .activeDeadlineSeconds }}
      restartPolicy: {{ default "Never" .restartPolicy }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      containers:
        - name: start
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          command: ["sh","/etc/mongosync/start.sh"]
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 50m
              memory: 32Mi
          volumeMounts:
            - name: config
              mountPath: /etc/mongosync
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: {{ include "mongosync.fullname" . }}
            defaultMode: 288
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
