apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service-common.fullname" . }}
  labels:
    {{- include "service-common.labels" . | nindent 4 }}
data:
  haproxy.sh: |
    #!/bin/sh
    set -e

    umask 177
    touch /run/haproxy_state
    cat /etc/ssl/tlscerts/tls.crt /etc/ssl/tlscerts/tls.key /etc/ssl/tlscerts/ca.crt > /run/server.pem
    exec /usr/local/sbin/haproxy -f /usr/local/etc/haproxy/haproxy.cfg

  haproxy.cfg: |
    global
      maxconn 8192
      ssl-default-server-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
      ssl-default-server-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets
      ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
      ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384
      ssl-default-bind-options prefer-client-ciphers no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets

      stats socket /tmp/haproxy.sock mode 600 level admin
      log stdout len 65535 format raw local0 info

    resolvers clusterdns
      parse-resolv-conf
      resolve_retries  3
      timeout resolve 1s
      timeout retry   1s
      hold other     60s
      hold refused   30s
      hold nx        30s
      hold timeout   30s
      hold valid     60s
      hold obsolete  60s

    defaults
      mode tcp
      option  dontlognull
      timeout connect         4s
      timeout server          86400s
      timeout client          86400s
      timeout http-keep-alive 1m
      default-server init-addr libc,none

      log global
      log-format '{"remote_addr":"%ci","backend":"%b","retries":%rc,"bytes_read":%B,"bytes_uploaded":%U,"cons":%fc}'

    frontend stats
      mode http
      bind *:8404
      http-request use-service prometheus-exporter if { path /metrics }
      stats enable
      stats uri /
      stats refresh 10s
      stats admin if LOCALHOST
      stats hide-version
      monitor-uri /healthz
      option dontlognull
      option clitcpka
      fullconn 16

    # services
    {{- range $key, $value := .Values.service.ports }}
    frontend {{ .name }}
      bind *:{{ .port }} ssl verify required crt /run/server.pem ca-file /etc/ssl/tlscerts/ca.crt
      option clitcpka
      use_backend {{ .name }}
    backend {{ .name }}
      mode tcp
      option   tcp-check
      balance  leastconn
      fullconn 512

      default-server check inter 15s fall 1 rise 1 on-marked-down shutdown-sessions resolve-prefer ipv4
      server {{ .name }} {{ .backend }} resolvers clusterdns
    {{- end }}
