apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-common.fullname" . }}
  labels:
    {{- include "service-common.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $value := .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "service-common.selectorLabels" . | nindent 4 }}
