apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-rules.fullname" . }}
  labels:
    {{- include "prometheus-rules.labels" . | nindent 4 }}
data:
  {{- include "prometheus-rules.rules" . | nindent 2 }}: |
    groups:
    {{- include "rules" . | nindent 4 }}

{{- range $path, $bytes := .Files.Glob "rules/*.yml" }}
      # {{ base $path }}
{{ $.Files.Get $path | indent 6 }}
{{- end }}
