apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-rules.fullname" . }}
  labels:
    {{- include "prometheus-rules.labels" . | nindent 4 }}
data:
  rules.yml: |
    groups:
    {{- include "rules" . | nindent 4 }}
