apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-rules.fullname" . }}
  labels:
    {{- include "prometheus-rules.labels" . | nindent 4 }}
data:
  {{- include "prometheus-rules.rules" . | nindent 2 }}: |
    groups:
    {{- include "rules" . | nindent 4 }}

  static-rules.yml: |
    groups:
    {{- range $path, $bytes := .Files.Glob "rules/*.yml" }}
    # {{ base $path }}
    {{- $.Files.Get $path | nindent 4 }}
    {{- end }}
