apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openvpn.fullname" . }}
  labels:
    {{- include "openvpn.labels" . | nindent 4 }}
data:
  corefile: |
    # proxy/forward to Cloudflare DNS-over-TLS
    .:53 {
        errors
        health {
           lameduck 5s
        }
        forward . tls://1.1.1.1 tls://1.0.0.1 {
            tls_servername cloudflare-dns.com
            policy sequential
            health_check 30s
            expire 60s
        }
        cache 300
        reload
    }

  init.sh: |-
    #!/bin/sh
    iptables  -t nat -I POSTROUTING -o eth0 -j MASQUERADE ||:
    ip6tables -t nat -I POSTROUTING -o eth0 -j MASQUERADE ||:

  start.sh: |-
    #!/bin/sh
    mkdir -p /dev/net
    mknod /dev/net/tun c 10 200
    exec openvpn --config /etc/openvpn/server/server.conf

  users.list: |-
    {{- if .Values.certManager.clients }}{{- range $k := .Values.certManager.clients }}
    {{ regexSplit "@" ($k | trunc 63 | trimAll ".") 2 | first }}
    {{- end }}{{- end }}

  server.conf: |-
    #
    port  {{ .Values.service.port }}
    proto {{ .Values.service.proto | lower }}4
    proto {{ .Values.service.proto | lower }}6

    dev tun
    dev-type tun
    mssfix 1220

    keepalive 10 120
    user openvpn
    group openvpn
    persist-key
    persist-tun
    verb 2
    mute 20
    status-version 2

    mode server
    tls-server
    tls-version-min 1.3
    tls-cipher TLS-ECDHE-ECDSA-WITH-CHACHA20-POLY1305-SHA256:TLS-ECDHE-RSA-WITH-CHACHA20-POLY1305-SHA256:TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256:TLS-ECDHE-RSA-WITH-AES-256-GCM-SHA384
    {{- if .Values.certManager.createCerts }}
    ecdh-curve prime256v1
    {{- end }}
    verify-client-cert require
    remote-cert-tls client

    {{- if .Values.openvpn.config }}
    {{- .Values.openvpn.config | nindent 4 }}
    {{- else }}
    server 172.30.0.0 255.255.255.0
    topology p2p

    data-ciphers AES-256-GCM:AES-128-GCM
    data-ciphers-fallback AES-256-CBC

    push "dhcp-option DNS 172.30.0.1"
    {{- end }}
    {{- if .Values.openvpn.redirectGateway }}
    push "redirect-gateway def1"
    {{- end }}

    client-config-dir /etc/openvpn/users

    {{- if .Values.openvpn.otp }}
    plugin /usr/lib/openvpn/plugins/openvpn-plugin-auth-pam.so "openvpn login USERNAME password PASSWORD pin OTP"
    auth-user-pass-optional
    auth-gen-token 36000
    reneg-sec 3600
    {{- end }}

    ca   /etc/openvpn/certs/ca.crt
    cert /etc/openvpn/certs/tls.crt
    key  /etc/openvpn/certs/tls.key
    {{- if .Values.openvpn.dh }}
    dh /etc/openvpn/auth/dh.pem
    {{- else }}
    dh none
    {{- end }}
    {{- if .Values.openvpn.tlsauth }}
    tls-auth /etc/openvpn/auth/tlsauth.key 0
    {{- end }}

    {{- if .Values.openvpn.revoke }}
    <crl-verify>
    {{ .Values.openvpn.revoke | nindent 4 }}
    </crl-verify>
    {{- end }}

  client.conf: |-
    client
    dev tun
    proto {{ .Values.service.proto | lower }}
    remote {{ .Values.openvpn.hostName }} {{ default "30190" .Values.service.nodePort }}
    resolv-retry infinite
    ping 10
    ping-restart 120
    mute 4
    mute-replay-warnings

    nobind
    persist-key
    persist-tun
    auth-nocache
    {{- if .Values.openvpn.otp }}
    auth-user-pass # pass
    static-challenge "Enter 2FA token: " 0
    {{- end }}
    data-ciphers AES-256-GCM:AES-256-CBC
    remote-cert-tls server

    {{- $ca := lookup "v1" "Secret" .Release.Namespace (include "openvpn.fullname" .) }}
    {{- if and .Values.certManager.createCerts $ca }}
    <ca>
    {{- get $ca.data "ca.crt" | b64dec | nindent 4 -}}
    </ca>
    {{- else }}
    ca   ca.crt
    {{- end }}
    cert client.crt
    key  client.key
    {{- if .Values.openvpn.dh }}
    <dh>
    {{- .Values.openvpn.dh | nindent 4 -}}
    </dh>
    {{- end }}
    {{- if .Values.openvpn.tlsauth }}
    key-direction 1
    <tls-auth>
    {{- .Values.openvpn.tlsauth | nindent 4 -}}
    </tls-auth>
    {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openvpn.fullname" . }}-users
  labels:
    {{- include "openvpn.labels" . | nindent 4 }}
data:
  DEFAULT: |-
    {{- if .Values.openvpn.defaultroutes }}
    {{- .Values.openvpn.defaultroutes | nindent 4 }}
    {{- end }}
