apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ipsec.fullname" . }}
  labels:
    {{- include "ipsec.labels" . | nindent 4 }}
type: Opaque
data:
  ipsec.secrets: {{ include "ipsec.secrets" . | b64enc }}
  ipsec.passwd: {{ include "ipsec.passwd" . | b64enc }}
  ipsec.conf: {{ include "ipsec.conf" . | b64enc }}
