apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tailscale.fullname" . }}
  labels:
    {{- include "tailscale.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $name, $value := .Values.tailscale }}
  {{ $name }}: {{ $value | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tailscale.fullname" . }}-state
  labels:
    {{- include "tailscale.labels" . | nindent 4 }}
type: Opaque
data:
