apiVersion: v1
kind: Service
metadata:
  name: {{ include "tailscale.fullname" . }}
  labels:
    {{- include "tailscale.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: socks
      protocol: TCP
      name: socks
  selector:
    {{- include "tailscale.selectorLabels" . | nindent 4 }}
{{- if .Values.service.p2pPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tailscale.fullname" . }}-p2p
  labels:
    {{- include "tailscale.labels" . | nindent 4 }}
spec:
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Local
  ipFamilyPolicy: PreferDualStack
  ports:
    - port: {{ .Values.service.p2pPort }}
      nodePort: {{ .Values.service.p2pPort }}
      targetPort: p2p
      protocol: UDP
      name: p2p
  selector:
    {{- include "tailscale.selectorLabels" . | nindent 4 }}
{{- end }}
