apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgbouncer.fullname" . }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
data:
  pgbouncer.ini: |-
    {{- include "pgbouncer.ini" . | nindent 4 }}

  pg_hba.conf: |-
    local   pgbouncer   pgbouncer                             trust
    local   pgbouncer   pgmetrics                             trust
    host    pgbouncer   pgbouncer             127.0.0.1/32    md5
    host    pgbouncer   pgmetrics             127.0.0.1/32    md5
  {{- if .Values.pgHbaConfiguration }}
    {{- .Values.pgHbaConfiguration | nindent 4 }}
  {{- end }}
