apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgbouncer.fullname" . }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
type: Opaque
data:
  userlist.txt: {{ include "userlist.txt" . | b64enc | quote }}
  pgmetricsPassword: {{ include "pgbouncer.pgmetricsPassword" . | b64enc }}
  pgmetricsURL: {{ include "pgbouncer.pgmetricsUrl" . | b64enc }}
