apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keydb.fullname" . }}
  labels:
    {{- include "keydb.labels" . | nindent 4 }}
data:
  {{- $name := include "keydb.fullname" . }}
  {{- $port := include "keydb.port" . }}

  init.sh: |
    #!/bin/sh
    set -e

    install -m 0660 -c /etc/keydb-common-config/keydb.conf /etc/keydb/keydb.conf

  {{ if eq .Values.keydb.activeReplica "yes" }}
    echo "# replicas">> /etc/keydb/keydb.conf
    for node in {{ range $i := until (int .Values.replicaCount) }} {{ $i }}{{ end }}; do
      if [ "${HOSTNAME}" != "{{ $name }}-${node}" ]; then
          echo "replicaof {{ $name }}-${node}.{{ $name }}-headless {{ $port }}" >> /etc/keydb/keydb.conf
      fi
    done
  {{- else }}
    if [ "$HOSTNAME" != "{{ $name }}-0" ]; then
      echo "replicaof {{ $name }}-0.{{ $name }}-headless {{ $port }}" >> /etc/keydb/keydb.conf
    fi
  {{- end }}

  {{- if .Values.backup.recovery }}
    [ -f /data/keydb.rdb ] || /entrypoint.d/restore.sh
  {{- end }}

  haproxy.sh: |
    #!/bin/sh
    set -e

    umask 177
    touch /run/haproxy_state
    cat /etc/ssl/tlscerts/tls.crt /etc/ssl/tlscerts/tls.key /etc/ssl/tlscerts/ca.crt > /run/server.pem

  backup.sh: |
    #!/bin/sh
    set -e

    wal-g --config /etc/walg/walg.yaml backup-push
    {{- if .Values.backup.cleanPolicy }}
    wal-g --config /etc/walg/walg.yaml delete {{ .Values.backup.cleanPolicy }} --confirm ||:
    {{- end }}
    wal-g --config /etc/walg/walg.yaml backup-list --detail

  restore.sh: |
    #!/bin/sh
    set -e

    wal-g --config /etc/walg/walg.yaml backup-list --detail
    wal-g --config /etc/walg/walg.yaml backup-fetch LATEST
    mv /data/dump.rdb /data/keydb.rdb

  restore-check.sh: |
    #!/bin/sh
    set -e

    /entrypoint.d/restore.sh
    redis-server --dbfilename keydb.rdb --dir /data --daemonize yes --pidfile /tmp/keydb.pid
    sleep 5

    echo "*** Size of the database ***"
    redis-cli info keyspace
    [ -f /tmp/keydb.pid ] && kill $(cat /tmp/keydb.pid) ||:

  redis-cli.sh: |
    #!/usr/bin/env bash

    FILENAME=$(mktemp -p /data --suffix=redis-cli-stderr)
    redis-cli $@ --rdb - 2>$FILENAME
    exit_code=$?
    cat $FILENAME >&2
    grep "Fail to fsync" $FILENAME | grep -q "Invalid argument"
    FAILED=$?
    rm $FILENAME;
    if [[ $exit_code -ne 0 ]] ; then
        test 0 -eq $FAILED || exit $exit_code
    fi
    exit 0
