{{- if semverCompare ">=1.22" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: policy/v1
{{- else -}}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "keydb.fullname" . }}
  labels:
    {{- include "keydb.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "keydb.selectorLabels" . | nindent 6 }}
  maxUnavailable: 1
