# Default values for prometheus-rules.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

## Create default rules for monitoring the cluster
##
defaultRules:
  create: true

  runbookUrl: "https://runbooks.prometheus-operator.dev/runbooks"

  rules:
    alertmanager: true
    etcd: false
    configReloaders: false
    general: true
    k8s: true
    kubeApiserverAvailability: true
    kubeApiserverBurnrate: true
    kubeApiserverHistogram: true
    kubeApiserverSlos: true
    kubeControllerManager: true
    kubelet: true
    kubePrometheusGeneral: true
    kubePrometheusNodeRecording: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    kubeSchedulerAlerting: true
    kubeSchedulerRecording: true
    kubeStateMetrics: true
    network: true
    node: true
    nodeExporterAlerting: true
    nodeExporterRecording: true
    prometheus: true
    prometheusOperator: false

  ## Disabled PrometheusRule alerts
  disabled:
    Watchdog: true
    # KubeAPIDown: true
    # NodeRAIDDegraded: true
