apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clickhouse.fullname" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
data:
  users.xml: |-
    <clickhouse>
        <profiles>
            <default>
                <max_memory_usage>10000000000</max_memory_usage>
                <use_uncompressed_cache>0</use_uncompressed_cache>
                <load_balancing>random</load_balancing>
            </default>
            <reader>
                <max_memory_usage>10000000000</max_memory_usage>
                <use_uncompressed_cache>0</use_uncompressed_cache>
                <load_balancing>random</load_balancing>
                <readonly>1</readonly>
            </reader>
        </profiles>
        <quotas>
            <default>
                <interval>
                    <duration>3600</duration>
                    <queries>0</queries>
                    <errors>0</errors>
                    <result_rows>0</result_rows>
                    <read_rows>0</read_rows>
                    <execution_time>0</execution_time>
                </interval>
            </default>
        </quotas>
        <users replace="replace">
        {{- range .Values.clickhouse.users }}
            <{{ .name }}>
                <password_sha256_hex>{{ .password }}</password_sha256_hex>
                <profile>{{ .profile | default "default" }}</profile>
                <quota>{{ .quota | default "default" }}</quota>
                <networks>
                    <ip>::/0</ip>
                    <ip>0.0.0.0/0</ip>
                </networks>
            </{{ .name }}>
        {{- end }}
        </users>
    </clickhouse>

  dictionaries.xml: |-
    <dictionaries>
    </dictionaries>

  config.xml: |-
    <clickhouse>
        <listen_host>::</listen_host>
        <listen_try>1</listen_try>

        <mysql_port></mysql_port>
        <postgresql_port></postgresql_port>

        <logger>
            <level>information</level>
            <console>1</console>
            <size>1000M</size>
            <count>2</count>
            <log>/var/log/clickhouse/clickhouse-server.log</log>
        </logger>
        <errorlog>/var/log/clickhouse/clickhouse-server.err.log</errorlog>

        {{- if .Values.metrics.enabled }}
        <prometheus>
            <endpoint>/metrics</endpoint>
            <port>9363</port>
            <metrics>true</metrics>
            <events>true</events>
            <asynchronous_metrics>false</asynchronous_metrics>
            <status_info>true</status_info>
        </prometheus>
        {{- end }}
        {{- default "" .Values.config | nindent 8 }}
    </clickhouse>

  storage.xml: |-
    <clickhouse>
        <storage_configuration>
            <disks>
                {{- range $key, $val := .Values.storage.disks }}
                <{{ $key }}>
                    {{- range $k, $v := $val }}
                    <{{ $k }}>{{ $v }}</{{ $k }}>
                    {{- end }}
                </{{ $key }}>
                {{- end }}
            </disks>
            <policies>
                {{- range $key, $val := .Values.storage.policies }}
                <{{ $key }}_policy>
                    <volumes>
                        <default>
                            <disk>{{ default "default" (get (default (dict) $val) "default_disk") }}</disk>
                        </default>
                        {{- if $val }}
                        <{{ $key }}>
                            {{- range $k, $v := $val }}
                            {{- if not (has $k (list "move_factor" "default_disk")) }}
                            <{{ $k }}>{{ $v }}</{{ $k }}>
                            {{- end }}
                            {{- end }}
                        </{{ $key }}>
                        {{- end }}
                    </volumes>
                    {{- if $val }}
                    <move_factor>{{ default "0.1" (get $val "move_factor") }}</move_factor>
                    {{- end }}
                </{{ $key }}_policy>
                {{- end }}
            </policies>
        </storage_configuration>
    </clickhouse>
