apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mongodb-backup.fullname" . }}
  labels:
    {{- include "mongodb-backup.labels" . | nindent 4 }}
data:
  backup.sh: |
    #!/bin/sh
    set -e

    export HOME=/var/backups

    wal-g --config /etc/walg/walg.yaml backup-push
    wal-g --config /etc/walg/walg.yaml backup-list
    {{- if .Values.cleanPolicy }}
    wal-g --config /etc/walg/walg.yaml delete {{ .Values.cleanPolicy }} --confirm ||:
    {{- end }}

  restore-init.sh: |
    #!/bin/sh
    set -e

    rm -rf /bitnami/mongodb/data/db

  restore.sh: |
    #!/bin/sh
    set -e

    export HOME=/var/backups

    wal-g --config=/etc/walg/walg-check.yaml backup-fetch LATEST
