apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb-backup.fullname" . }}
  labels:
    {{- include "mongodb-backup.labels" . | nindent 4 }}
type: Opaque
data:
  walg.yaml: {{ include "mongodb-backup.walg" . | b64enc }}
