# Default values for mongosqld.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/sergelogvinov/mongosqld
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

tlsCerts:
  create: true

schemaMode: memory
schema: ~
  # schema:
  # - db: mongoDb
  #   tables:
  #   - table: table
  #     collection: table
  #     pipeline: []
  #     columns:
  #     - Name: _id
  #       MongoType: bson.ObjectId
  #       SqlName: _id
  #       SqlType: objectid

config: ""
auth:
  host: mongo-backend-rs0:27017
  username: user
  password: pass
  database: db

args: []
  # - --sampleNamespaces=contacts.addresses

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534
  fsGroup: 65534
  fsGroupChangePolicy: "OnRootMismatch"

securityContext:
  seccompProfile:
    type: RuntimeDefault
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL

service:
  type: ClusterIP
  port: 3306

resources:
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
