# Default values for bitwarden.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: vaultwarden/server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

envs:
  SMTP_USERNAME: 'username'
  SMTP_PASSWORD: 'password'
  # /vaultwarden hash
  ADMIN_TOKEN: 'token'
  DISABLE_ADMIN_TOKEN: 'false'

config:
  SMTP_HOST: 'smtp.domain.tld'
  SMTP_FROM: 'bitwarden-rs@domain.tld'
  SMTP_FROM_NAME: 'Betmaster Vault'
  SMTP_PORT: 587
  SMTP_SSL: true
  #
  WEB_VAULT_ENABLED: true
  WEBSOCKET_ENABLED: true
  ROCKET_WORKERS: 10
  #
  EXTENDED_LOGGING: true
  ROCKET_CLI_COLORS: 'off'
  #
  SIGNUPS_ALLOWED: false
  SIGNUPS_VERIFY: false
  SIGNUPS_DOMAINS_WHITELIST: 'domain.tld'
  INVITATIONS_ALLOWED: true
  INVITATION_ORG_NAME: 'Bitwarden'
  SHOW_PASSWORD_HINT: false
  #
  USER_ATTACHMENT_LIMIT: 1048576
  ORG_ATTACHMENT_LIMIT: 1048576

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 33
  runAsGroup: 33
  fsGroup: 33
  fsGroupChangePolicy: "OnRootMismatch"

securityContext:
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
  runAsUser: 33
  runAsGroup: 33
  # readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 80
  portWSocket: 3012

ingress:
  enabled: false
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/limit-connections: "25"
    nginx.ingress.kubernetes.io/limit-rps: "15"
  hosts:
    - host: chart-example.local

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  enabled: false
  ## A manually managed Persistent Volume and Claim
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:
  # storageClass: "-"
  accessModes: [ReadWriteOnce]
  size: 10Gi
  annotations: {}

nodeSelector: {}

tolerations: []

affinity: {}
