apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgbouncer.fullname" . }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $pgmetricsPassword := include "pgbouncer.pgmetricsPassword" . }}
  {{- $data := dict "userlist" .Values.userlist "pgmetricsPassword" $pgmetricsPassword }}
  userlist.txt: {{ include "userlist.txt" $data | b64enc }}
  pgmetricsPassword: {{ $pgmetricsPassword | b64enc }}
  pgmetricsURL: {{ printf "postgres://pgmetrics:%s@127.0.0.1:5432/pgbouncer" $pgmetricsPassword | b64enc }}
