apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgbouncer.fullname" . }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $pgmetricsPassword := include "pgbouncer.pgmetricsPassword" . }}
  {{- $data := dict "userlist" .Values.userlist "pgmetricsPassword" $pgmetricsPassword }}
  userlist.txt: {{ include "userlist.txt" $data | b64enc | quote }}
  pgmetricsPassword: {{ $pgmetricsPassword | b64enc | quote }}
  pgmetricsURL: {{ printf "postgres://pgmetrics:%s@127.0.0.1:5432/pgbouncer" $pgmetricsPassword | b64enc }}
  {{- $ca := genCA "openvpn" 3650 }}
  {{- $server := genSignedCert "server" nil nil 3650 $ca }}
  serverTLSca: {{ default $ca.Cert .Values.serverSsl.ca | b64enc | quote }}
  serverTLScert: {{ default $server.Cert .Values.serverSsl.cert | b64enc | quote }}
  serverTLSkey: {{ default $server.Key .Values.serverSsl.key | b64enc | quote }}
