apiVersion: v1
kind: Secret
metadata:
  name: {{ include "link-common.fullname" . }}
  labels:
    {{- include "link-common.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.wireguard.enabled }}
  wg0.conf: {{ include "link-common-wireguard.conf" . | b64enc }}
{{- end}}
