{{- if and .Values.backupCheck.enabled (ne .Values.backupCheck.schedule "") }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-{{ include "postgresql-single.fullname" . }}-backup-check
  labels:
    {{- with .Values.podlabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- include "postgresql-single.crontab.labels" . | nindent 4 }}
    app.kubernetes.io/component: checker
{{- with .Values.backupCheck.persistence.annotations }}
  annotations:
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
spec:
  accessModes:
  {{- range .Values.backupCheck.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backupCheck.persistence.size | quote }}
{{- if .Values.backupCheck.persistence.storageClass }}
{{- if (eq "-" .Values.backupCheck.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.backupCheck.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
