apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bitwarden.fullname" . }}
  labels:
    {{- include "bitwarden.labels" . | nindent 4 }}
data:
  config.json: {{ toJson .Values.config | lower | quote }}
