apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mongodb-backup.fullname" . }}
  labels:
    {{- include "mongodb-backup.labels" . | nindent 4 }}
data:
  backup.sh: |
    #!/bin/sh
    set -e

    wal-g --config /etc/walg/walg.yaml backup-push
    wal-g --config /etc/walg/walg.yaml backup-list
