apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clickhouse.fullname" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
data:
  users.xml: |-
    <yandex>
        <profiles>
            <default>
                <max_memory_usage>10000000000</max_memory_usage>
                <use_uncompressed_cache>0</use_uncompressed_cache>
                <load_balancing>random</load_balancing>
            </default>
            <reader>
                <max_memory_usage>10000000000</max_memory_usage>
                <use_uncompressed_cache>0</use_uncompressed_cache>
                <load_balancing>random</load_balancing>
                <readonly>1</readonly>
            </reader>
        </profiles>
        <quotas>
            <default>
                <interval>
                    <duration>3600</duration>
                    <queries>0</queries>
                    <errors>0</errors>
                    <result_rows>0</result_rows>
                    <read_rows>0</read_rows>
                    <execution_time>0</execution_time>
                </interval>
            </default>
        </quotas>
        {{- range .Values.clickhouse.users }}
        <users incl="users" replace="replace">
            <{{ .name }}>
                <password_sha256_hex>{{ .password }}</password_sha256_hex>
                <profile>{{ .profile | default "default" }}</profile>
                <quota>{{ .quota | default "default" }}</quota>
                <networks>
                    <ip>::/0</ip>
                </networks>
            </{{ .name }}>
        </users>
        {{- end }}
    </yandex>

  dictionaries.xml: |-
    <dictionaries>
    </dictionaries>
