{{- if eq .Values.schemaMode "custom" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "mongosqld.fullname" . }}-schema
  labels:
    {{- include "mongosqld.labels" . | nindent 4 }}
    app.kubernetes.io/component: schema
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-weight": {{ default "-15" .weight | quote }}
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: 1800
  activeDeadlineSeconds: 600
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        {{- include "mongosqld.labels" . | nindent 8 }}
        app.kubernetes.io/component: schema
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      serviceAccountName: {{ include "mongosqld.serviceAccountName" . }}
      activeDeadlineSeconds: 600
      restartPolicy: "Never"
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-schema
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh","/etc/mongosqld/schema-upload.sh"]
          volumeMounts:
            - name: config
              mountPath: /etc/mongosqld
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: {{ include "mongosqld.fullname" . }}
            defaultMode: 256
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
