apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongosqld.fullname" . }}
  labels:
    {{- include "mongosqld.labels" . | nindent 4 }}
type: Opaque
data:
  mongosqld.conf: {{ include "mongosqld.commonConfig" . | b64enc }}
{{- if .Values.schema }}
  schema.drdl: {{ .Values.schema | b64enc }}
{{- end }}
  schema-upload.sh: {{ include "mongosqld.schemaUpload" . | b64enc }}
