# Default values for mongodb-backup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/sergelogvinov/mongodb
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

schedule: "0 1 * * *"
cleanPolicy: "retain 3 --retain-count 3"
activeDeadlineSeconds: 3600 # 1h

backupCheck:
  enabled: false
  schedule: "15 8 * * *"

  resources:
    limits:
      cpu: 2
      memory: 1Gi
    requests:
      cpu: 2
      memory: 512Mi

  persistence:
    ## A manually managed Persistent Volume and Claim
    # existingClaim:
    #
    # storageClass: "-"
    accessModes:
      - ReadWriteOnce
    size: 8Gi
    annotations: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

auth:
  host: mongo-headless:27017/?authSource=admin
  username: root
  password: root

env: []

# walg: |
#   GOOGLE_APPLICATION_CREDENTIALS: /etc/gcp/backup.json

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podLabels: {}
podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 34
  runAsGroup: 0
  fsGroup: 34
  fsGroupChangePolicy: "OnRootMismatch"

securityContext:
  # seccompProfile:
  #   type: RuntimeDefault
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL

resources:
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 500m
    memory: 256Mi

# extraVolumes:
#   - name: gcp-certs
#     secret:
#       defaultMode: 256
#       secretName: backup-gcp
# extraVolumeMounts:
#   - name: gcp-certs
#     mountPath: /etc/gcp
#     readOnly: true

persistence:
  enabled: false
  ## A manually managed Persistent Volume and Claim
  ## If defined, PVC must be created manually before volume will be bound
  existingClaim: ""
  # storageClass: "-"
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  annotations: {}

nodeSelector: {}

tolerations: []

affinity: {}
