- name: node-exporter
  rules:
  - alert: RaidStatus
    expr: node_md_blocks - node_md_blocks_synced > 0
    for: 10m
    labels:
      severity: warning
    annotations:
      description: The raid on {{ $labels.kubernetes_node_name }} {{ $labels.device }} is syncing {{ $labels.value }}
      summary: MD-Raid on node is syncing
  - alert: MD Raid not in Active state
    expr: node_md_state{state!~"active"} == 1
    for: 5h
    labels:
      infrastructure: true
    annotations:
      description: "MD Raid {{$labels.device}} is in {{$labels.state}} state on {{$labels.kubernetes_node_name}} node"

  - alert: NVME disk is overheated
    expr: node_hwmon_temp_celsius{chip=~"^0000.*",sensor=~"temp.+"} > 65
    for: 20m
    labels:
      infrastructure: true
    annotations:
      description: "NVME disk (chip id {{$labels.chip}} on node {{$labels.kubernetes_node_name}} is overheated ({{$value}}'C)"
